version: "3.8"

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  jaeger:
    image: jaegertracing/all-in-one:1.38
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
      - "14317:4313"
      - "14318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true      

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.62.1
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./docker-compose-files/otel-collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
    depends_on:
      - zipkin
      - jaeger

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./docker-compose-files/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
      
  grafana:
    container_name: collector.grafana
    image: grafana/grafana:9.1.7
    ports:
      - "3000:3000"
    volumes:
      - ./docker-compose-files/prometheus_ds.yml:/etc/grafana/provisioning/datasources/prometheus_ds.yml
    depends_on:
      - prometheus

